import arrow

#PEGA A DATA E A HORA QUE ESTÁ NO MOMENTO,E MOSTRA NO FORMATO QUE ESCOLHI / POREM NO SERVIDOR ELE MOSTRA A HORA DO SERVIDOR E NÃO DA MAQUINA
now = arrow.now()
print(now.format('DD-MM-YYYY HH:mm:ss'))
